name: Auto Deploy to GitHub Pages

# Trigger on every push to main
on:
  push:
    branches:
      - main

# Grant GITHUB_TOKEN the rights to push
permissions:
  contents: write     # allow pushing commits
  pages: write        # allow updating GitHub Pages
  id-token: write     # (only if you use OIDC in other steps)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (Optional) If you need Node.js—for e.g. React/Vue/Svelte—set it up
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Write env file
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env

      # 4. Run your build (adjust to your framework)
      - name: Build site
        run: npm run build

      # 5. Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Built-in token has permission to push to gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Directory to publish (e.g. 'build' for Create React App)
          publish_dir: ./dist
          # If your pages live at root (not in /docs), add:
          # publish_branch: gh-pages